/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connectionDB.connection;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;  
import javax.sql.rowset.WebRowSet; 
import com.sun.rowset.WebRowSetImpl;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 *
 * @author Pedro Humberto Sylvestre Nunes, Guilherme Mendes Mariano, Jorge Danillo Pereira, Jaffer da Silva Camacam Santos e Alexandre Morais Borges
 */
public class Controle_estoque extends javax.swing.JFrame {
    String myUrl = "jdbc:mysql://localhost:3306/santos_inocentes?useTimezone=true&serverTimezone=UTC";
    private static final String USER = "ong";
    private static final String PASS = "santos123@";
    Tela_Principal Tela_Principal;
    Historico Historico;
    /**
     * Creates new form
     */
    public Controle_estoque() {
        initComponents();
        setIcon();
        this.setTitle("Controle de Estoque");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CONTROLEDEESTOQUE = new javax.swing.JLabel();
        jL_Produto = new javax.swing.JLabel();
        jCom_produto = new javax.swing.JComboBox<>();
        jL_Quantidade = new javax.swing.JLabel();
        jT_quantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_QuantidadeMinima = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ok1 = new javax.swing.JButton();
        Ok2 = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        BtHistorico = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jChange1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jChange8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jChange4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jChange2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jChange5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jChange7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jChange6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jChange9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jChange3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CONTROLEDEESTOQUE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CONTROLEDEESTOQUE.setText("Controle de Estoque");

        jL_Produto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jL_Produto.setText("Produto:");

        jCom_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        try {
            Connection con = DriverManager.getConnection(myUrl, USER, PASS);
            String query = "SELECT nome FROM produtos order by nome";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            ArrayList<String> names = new ArrayList<String>();

            while (rs.next()) {
                //            names.add(rs.getString(1));
                jCom_produto.addItem(rs.getString(1));
                System.out.println(names);
            }
            //            jCom_Produto.addItem(names);

        } catch (SQLException ex) {
            Logger.getLogger(Gerenciar_produto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jCom_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_produtoActionPerformed(evt);
            }
        });

        jL_Quantidade.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jL_Quantidade.setText("Quantidade:");

        jT_quantidade.setEditable(false);
        jT_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_quantidadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Quantidade");

        jT_QuantidadeMinima.setEditable(false);
        jT_QuantidadeMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_QuantidadeMinimaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ótimo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Movimentação:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("mínima:");

        Ok1.setBackground(new java.awt.Color(204, 204, 204));
        Ok1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ok1.setForeground(new java.awt.Color(0, 153, 255));
        Ok1.setText("Gerar Gráfico");
        Ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok1ActionPerformed(evt);
            }
        });

        Ok2.setBackground(new java.awt.Color(204, 204, 204));
        Ok2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ok2.setForeground(new java.awt.Color(0, 153, 255));
        Ok2.setText("Gerar Arquivo .xls");
        Ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok2ActionPerformed(evt);
            }
        });

        Voltar.setBackground(new java.awt.Color(204, 204, 204));
        Voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voltar.setForeground(new java.awt.Color(0, 153, 255));
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        BtHistorico.setBackground(new java.awt.Color(204, 204, 204));
        BtHistorico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtHistorico.setForeground(new java.awt.Color(0, 153, 255));
        BtHistorico.setText("Histórico");
        BtHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHistoricoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Estado:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Unidade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Quantidade");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jChange1.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jChange8.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChange8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jChange4.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jChange2.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jChange5.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Data");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jChange7.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChange7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jChange6.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jChange9.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChange9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jChange3.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChange3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChange3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel10, jPanel11, jPanel12, jPanel13, jPanel21, jPanel22, jPanel23, jPanel3, jPanel5, jPanel6, jPanel8, jPanel9});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/santos_4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Quantidade)
                            .addComponent(jT_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jT_QuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8))
                            .addComponent(jLabel4))
                        .addGap(209, 209, 209)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Produto)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CONTROLEDEESTOQUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCom_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CONTROLEDEESTOQUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL_Produto)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCom_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jL_Quantidade)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(Ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_QuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ok1ActionPerformed

    private void Ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok2ActionPerformed
                try {  
            Connection con = connection.getConnection();
            PreparedStatement p = con.prepareStatement("SELECT * FROM produtos");
                    ResultSet rs = p.executeQuery();
                    WebRowSet wrs = new WebRowSetImpl();
                    wrs.populate(rs);
                    p.close();
                    con.close();
                    wrs.writeXml(new FileOutputStream("output.xml"));
                    wrs.close();   
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Controle_estoque.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Controle_estoque.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Controle_estoque.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Controle_estoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Ok2ActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.dispose();
        Tela_Principal = new Tela_Principal();
        Tela_Principal.setLocationRelativeTo(null);
        Tela_Principal.setSize (780,500);
        Tela_Principal.setVisible(true);
        Tela_Principal.setResizable(false);
    }//GEN-LAST:event_VoltarActionPerformed

    private void BtHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHistoricoActionPerformed
       this.dispose();
        Historico = new Historico();
        Historico.setLocationRelativeTo(null);
        Historico.setSize (780,500);
        Historico.setVisible(true);
        Historico.setResizable(false);
    }//GEN-LAST:event_BtHistoricoActionPerformed

    private void jTex_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTex_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTex_PesquisaActionPerformed

    private void jCom_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_produtoActionPerformed
         String nome = (String)jCom_produto.getSelectedItem();
            try{
        Connection con = connection.getConnection();
        
        String query = "SELECT quantidade_total FROM produtos WHERE nome = '"+nome+"'";
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        JLabel jChange[] = new JLabel[10];
        jChange1.setText("");
        jChange2.setText("");
        jChange3.setText("");
        jChange4.setText("");
        jChange5.setText("");
        jChange6.setText("");
        jChange7.setText("");
        jChange8.setText("");
        jChange9.setText("");
        
        ArrayList<String> quantidadeTabela = new ArrayList<String>();
            while (rs.next()) { 
            quantidadeTabela.add(rs.getString(1));
            }
            String batata = quantidadeTabela.toString().replace("[","").replace("]","");
            jT_quantidade.setText(batata);
            
                        String queryMin = "SELECT quantidade_min FROM produtos WHERE nome = '"+nome+"'";
            Statement stMin = con.createStatement();
            ResultSet rsMin = stMin.executeQuery(queryMin);
            
            ArrayList<String> quantidadeMinTabela = new ArrayList<String>();
            while (rsMin.next()) { 
            quantidadeMinTabela.add(rsMin.getString(1));
            }
            String batata2 = quantidadeMinTabela.toString().replace("[","").replace("]","");
                System.out.println(batata2);
            jT_QuantidadeMinima.setText(batata2);
            int batatinha = Integer.parseInt(batata);
            int batatinha2 = Integer.parseInt(batata2);
            
            if (batatinha > batatinha2*2){
                jPanel2.setBackground(new Color(0,153,0));
                jLabel5.setText("Ótimo");
                jLabel5.setForeground(Color.BLACK);
//                ótimo
            }
            else if (batatinha2 <= batatinha && batatinha <= batatinha*2){
//                médio
                jPanel2.setBackground(new Color(255,204,0));
                jLabel5.setText("Médio");
                jLabel5.setForeground(Color.BLACK);
            }
            else{
                jPanel2.setBackground(new Color(204,0,0));
                jLabel5.setText("Baixo");
                jLabel5.setForeground(Color.BLACK);
//                Baixo[204,0,0]
            }
            String queryNCM = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement stNCM = con.createStatement();
            ResultSet rsNCM = stNCM.executeQuery(queryNCM);
        
            ArrayList<String> ncmList = new ArrayList<String>();

            while (rsNCM.next()) { 
                ncmList.add(rsNCM.getString(1));
            }
            String ncm1 = ncmList.toString().replace("[","").replace("]","");
            
            String queryHistorico = "SELECT date_format(M.data_movimentacao, '%d/%m/%Y'), M.quantidade, M.unidade_idunidade FROM movimentacao as M, produtos as P WHERE P.ncm = '"+ncm1+"' ORDER BY data_movimentacao DESC";
            Statement stHistorico = con.createStatement();
            ResultSet rsHistorico = stHistorico.executeQuery(queryHistorico);
            
            ArrayList<String> HistoricoTabela = new ArrayList<String>();
            while (rsHistorico.next()){
                if (jChange7.getText().equals("")){
                    jChange7.setText(rsHistorico.getString("date_format(M.data_movimentacao, '%d/%m/%Y')"));
                    jChange4.setText(rsHistorico.getString("quantidade"));
                    jChange1.setText(rsHistorico.getString("unidade_idunidade"));
                    if (jChange1.getText().equals("1")){
                        jChange1.setText("Casa das Mães");
                    }
                    else if (jChange1.getText().equals("2")){
                        jChange1.setText("Creche");
                    }
                    else if (jChange1.getText().equals("3")){
                        jChange1.setText("Descarte ou Outros");
                    }
                }
                else if (jChange8.getText().equals("")){
                    jChange8.setText(rsHistorico.getString("date_format(M.data_movimentacao, '%d/%m/%Y')"));
                    jChange5.setText(rsHistorico.getString("quantidade"));
                    jChange2.setText(rsHistorico.getString("unidade_idunidade"));
                    if (jChange2.getText().equals("1")){
                        jChange2.setText("Casa das Mães");
                    }
                    else if (jChange2.getText().equals("2")){
                        jChange2.setText("Creche");
                    }
                    else if (jChange2.getText().equals("3")){
                        jChange2.setText("Descarte ou Outros");
                    }
                }
                else if (jChange9.getText().equals("")){
                    jChange9.setText(rsHistorico.getString("date_format(M.data_movimentacao, '%d/%m/%Y')"));  
                    jChange6.setText(rsHistorico.getString("quantidade"));
                    jChange3.setText(rsHistorico.getString("unidade_idunidade"));
                    if (jChange3.getText().equals("1")){
                        jChange3.setText("Casa das Mães");
                    }
                    else if (jChange3.getText().equals("2")){
                        jChange3.setText("Creche");
                    }
                    else if (jChange3.getText().equals("3")){
                        jChange3.setText("Descarte ou Outros");
                    }
                }
                HistoricoTabela.add(rsHistorico.getString(1));
            }
                System.out.println("Saiu do Date");  
            
            }
            catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jCom_produtoActionPerformed

    private void jT_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_quantidadeActionPerformed
           String nome = (String)jCom_produto.getSelectedItem();
            try{
        Connection con = connection.getConnection();
        
        String query = "SELECT quantidade FROM produtos WHERE nome = '"+nome+"'";
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        
        ArrayList<String> quantidadeTabela = new ArrayList<String>();

            while (rs.next()) { 
            jT_quantidade.setText(rs.getString(1));
            }
            jT_quantidade.setText(quantidadeTabela.toString());
            } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_quantidadeActionPerformed

    private ArrayList<String> returnTabela1() throws ClassNotFoundException, SQLException{
                 String nome = (String)jCom_produto.getSelectedItem();
         Connection con = connection.getConnection();
    String queryNCM = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement stNCM = con.createStatement();
            ResultSet rsNCM = stNCM.executeQuery(queryNCM);
        
            ArrayList<String> ncmList = new ArrayList<String>();

            while (rsNCM.next()) { 
                ncmList.add(rsNCM.getString(1));
            }
            String ncm1 = ncmList.toString().replace("[","").replace("]","");
            
            String queryHistorico = "SELECT date_format(data_movimentacao, '%d/%m/%Y') FROM movimentacao, produtos as P WHERE P.ncm = '"+ncm1+"' ORDER BY data_movimentacao DESC";
            Statement stHistorico = con.createStatement();
            ResultSet rsHistorico = stHistorico.executeQuery(queryHistorico);
            
            ArrayList<String> HistoricoTabela = new ArrayList<String>();
            while (rsHistorico.next()){
                HistoricoTabela.add(rsHistorico.getString(1));
            }
            String Historico1 = HistoricoTabela.toString().replace("[","").replace("]","");
            return HistoricoTabela;
    }
    private ArrayList<String> returnTabela2() throws ClassNotFoundException, SQLException{
            String nome = (String)jCom_produto.getSelectedItem();
            Connection con = connection.getConnection();
            String queryNCM = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement stNCM = con.createStatement();
            ResultSet rsNCM = stNCM.executeQuery(queryNCM);
        
            ArrayList<String> ncmList = new ArrayList<String>();

            while (rsNCM.next()) { 
                ncmList.add(rsNCM.getString(1));
            }
            String ncm1 = ncmList.toString().replace("[","").replace("]","");
            String queryHistorico = "SELECT date_format(data_movimentacao, '%d/%m/%Y') FROM movimentacao, produtos as P WHERE P.ncm = '"+ncm1+"' ORDER BY data_movimentacao DESC";
            Statement stHistorico = con.createStatement();
            ResultSet rsHistorico = stHistorico.executeQuery(queryHistorico);
            
            ArrayList<String> HistoricoTabela = new ArrayList<String>();
            while (rsHistorico.next()){
                HistoricoTabela.add(rsHistorico.getString(1));
            }
            String Historico1 = HistoricoTabela.toString().replace("[","").replace("]","");
            String queryHistorico2 = "SELECT M.quantidade FROM movimentacao as M, produtos as P WHERE P.ncm = '"+ncm1+"' AND date_format(M.data_movimentacao, '%d/%m/%Y') = '"+Historico1+"' ORDER BY M.data_movimentacao DESC";
            Statement stHistorico2 = con.createStatement();
            ResultSet rsHistorico2 = stHistorico2.executeQuery(queryHistorico2);
            
            ArrayList<String> HistoricoTabela2 = new ArrayList<String>();
            while (rsHistorico2.next()){
                HistoricoTabela2.add(rsHistorico2.getString(1));
            }
            String Historico2 = HistoricoTabela2.toString().replace("[","").replace("]","");
            return HistoricoTabela2;
    }
    
    private ArrayList<String> returnTabela3() throws SQLException, ClassNotFoundException{
        String nome = (String)jCom_produto.getSelectedItem();
         Connection con = connection.getConnection();
         String queryNCM = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement stNCM = con.createStatement();
            ResultSet rsNCM = stNCM.executeQuery(queryNCM);
        
            ArrayList<String> ncmList = new ArrayList<String>();

            while (rsNCM.next()) { 
                ncmList.add(rsNCM.getString(1));
            }
            String ncm1 = ncmList.toString().replace("[","").replace("]","");
            String queryHistorico = "SELECT date_format(data_movimentacao, '%d/%m/%Y') FROM movimentacao, produtos as P WHERE P.ncm = '"+ncm1+"' ORDER BY data_movimentacao DESC";
            Statement stHistorico = con.createStatement();
            ResultSet rsHistorico = stHistorico.executeQuery(queryHistorico);
            
            ArrayList<String> HistoricoTabela = new ArrayList<String>();
            while (rsHistorico.next()){
                HistoricoTabela.add(rsHistorico.getString(1));
            }
            String Historico1 = HistoricoTabela.toString().replace("[","").replace("]","");
            String queryHistorico3 = "SELECT M.unidade_idunidade FROM movimentacao as M, produtos as P WHERE P.ncm = '"+ncm1+"' AND date_format(M.data_movimentacao, '%d/%m/%Y') = '"+Historico1+"' ORDER BY M.data_movimentacao DESC";
            Statement stHistorico3 = con.createStatement();
            ResultSet rsHistorico3 = stHistorico3.executeQuery(queryHistorico3);
            
            ArrayList<String> HistoricoTabela3 = new ArrayList<String>();
            while (rsHistorico3.next()){
                HistoricoTabela3.add(rsHistorico3.getString(1));
            }
            String Historico3 = HistoricoTabela3.toString().replace("[","").replace("]","");
            return HistoricoTabela3;
    }
    
    private void jT_QuantidadeMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_QuantidadeMinimaActionPerformed
         String nome = (String)jCom_produto.getSelectedItem();
            try{
        Connection con = connection.getConnection();
        
        String query = "SELECT quantidade_min FROM produtos WHERE nome = '"+nome+"'";
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        
        ArrayList<String> quantidadeMin = new ArrayList<String>();

            while (rs.next()) { 
            quantidadeMin.add(rs.getString(1));
            }
            jT_QuantidadeMinima.setText(quantidadeMin.toString());
            } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_QuantidadeMinimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle_estoque().setVisible(true);
            }
        });
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Santos_2.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtHistorico;
    private javax.swing.JLabel CONTROLEDEESTOQUE;
    private javax.swing.JButton Ok1;
    private javax.swing.JButton Ok2;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jChange1;
    private javax.swing.JLabel jChange2;
    private javax.swing.JLabel jChange3;
    private javax.swing.JLabel jChange4;
    private javax.swing.JLabel jChange5;
    private javax.swing.JLabel jChange6;
    private javax.swing.JLabel jChange7;
    private javax.swing.JLabel jChange8;
    private javax.swing.JLabel jChange9;
    private javax.swing.JComboBox<String> jCom_produto;
    private javax.swing.JLabel jL_Produto;
    private javax.swing.JLabel jL_Quantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jT_QuantidadeMinima;
    private javax.swing.JTextField jT_quantidade;
    // End of variables declaration//GEN-END:variables
}
