/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connectionDB.connection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import produto.Produto;
import produto.ProdutoConecta;

/**
 *
 * @author Pedro Humberto Sylvestre Nunes, Guilherme Mendes Mariano, Jorge Danillo Pereira, Jaffer da Silva Camacam Santos e Alexandre Morais Borges
 */
public class Gerenciar_produto extends javax.swing.JFrame {
Tela_Principal Tela_Principal;
String myUrl = "jdbc:mysql://localhost:3306/santos_inocentes?useTimezone=true&serverTimezone=UTC";
private static final String USER = "ong";
private static final String PASS = "santos123@";
Date date = new Date();

    /**
     * Creates new form 
     */
    public Gerenciar_produto() {
        initComponents();
        setIcon();
        this.setTitle("Controle de Estoque - Gerenciar Produto");
        jTextNcm.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCom_Pr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCom_Produto = new javax.swing.JComboBox<>();
        Jl_descricao = new javax.swing.JLabel();
        jl_DataVencimento = new javax.swing.JLabel();
        Data_Vencimento = new javax.swing.JFormattedTextField();
        Jl_quantidade = new javax.swing.JLabel();
        Quantidade = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Voltar1 = new javax.swing.JButton();
        Voltar2 = new javax.swing.JButton();
        Jl_quantidade1 = new javax.swing.JLabel();
        Quantidade_min = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Descricao = new javax.swing.JTextArea();
        jCom_Unidade = new javax.swing.JComboBox<>();
        Jl_descricao1 = new javax.swing.JLabel();
        jTextNcm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCom_Produto1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCom_Pr.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Produto:");

        jCom_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jCom_Produto.setToolTipText(null);
        try {
            Connection con = DriverManager.getConnection(myUrl, USER, PASS);
            String query = "SELECT nome FROM produtos where char_length(nome) < 5 order by nome";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            ArrayList<String> names = new ArrayList<String>();

            while (rs.next()) {
                //            names.add(rs.getString(1));
                jCom_Produto.addItem(rs.getString(1));
                System.out.println(names);
            }

            String query2 = "select nome from produtos where ncm like \"2201.10.00\" union select nome from produtos where ncm like \"2209.00.00\" union select nome from produtos where ncm like \"2501.00\" union select nome from produtos where ncm like \"2101.11.10\" union select nome from produtos where ncm like \"0707.00.00\" union select nome from produtos where ncm like \"0409.00.00\" union select nome from produtos where ncm like \"0702.00.00\";";
            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery(query2);
            ArrayList<String> names2 = new ArrayList<String>();

            while (rs2.next()) {
                jCom_Produto.addItem(rs.getString(1));
            }
            //            jCom_Produto.addItem(names);

        } catch (SQLException ex) {
            Logger.getLogger(Gerenciar_produto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jCom_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_ProdutoActionPerformed(evt);
            }
        });

        Jl_descricao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jl_descricao.setText("Descrição:");

        jl_DataVencimento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_DataVencimento.setText("Data de Vencimento:");

        try{ MaskFormatter bdayFormatter = new MaskFormatter("##/##/####");
            bdayFormatter.setPlaceholderCharacter('_');
            Data_Vencimento = new JFormattedTextField(bdayFormatter);
            bdayFormatter.setValidCharacters("0123456789");
            Data_Vencimento.setColumns(10);

        }
        catch(Exception e){}
        Data_Vencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_VencimentoActionPerformed(evt);
            }
        });

        Jl_quantidade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jl_quantidade.setText("Quantidade:");

        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });

        Cadastrar.setBackground(new java.awt.Color(204, 204, 204));
        Cadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(0, 153, 255));
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Voltar1.setBackground(new java.awt.Color(204, 204, 204));
        Voltar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voltar1.setForeground(new java.awt.Color(0, 153, 255));
        Voltar1.setText("Voltar");
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });

        Voltar2.setBackground(new java.awt.Color(204, 204, 204));
        Voltar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voltar2.setForeground(new java.awt.Color(0, 153, 255));
        Voltar2.setText("Gerar Recibo");
        Voltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar2ActionPerformed(evt);
            }
        });

        Jl_quantidade1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jl_quantidade1.setText("Quantidade Mínima:");

        Quantidade_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantidade_minActionPerformed(evt);
            }
        });

        jT_Descricao.setColumns(20);
        jT_Descricao.setRows(5);
        jScrollPane1.setViewportView(jT_Descricao);

        jCom_Unidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramas", "Gramas", "Miligramas", "Litros", "Unidades", "Pacote", "Fardo", "Caixa" }));
        jCom_Unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_UnidadeActionPerformed(evt);
            }
        });

        Jl_descricao1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jl_descricao1.setText("Código NCM:");

        jTextNcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNcmActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/santos_4.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(220, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(96, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Produtos");

        jCom_Produto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jCom_Produto1.setToolTipText(null);
        jCom_Produto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_Produto1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Tipo:");

        javax.swing.GroupLayout jCom_PrLayout = new javax.swing.GroupLayout(jCom_Pr);
        jCom_Pr.setLayout(jCom_PrLayout);
        jCom_PrLayout.setHorizontalGroup(
            jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCom_PrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Voltar2)
                .addGap(18, 18, 18)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jCom_PrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCom_PrLayout.createSequentialGroup()
                        .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Jl_descricao1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jCom_PrLayout.createSequentialGroup()
                        .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jCom_PrLayout.createSequentialGroup()
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Quantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jl_quantidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jCom_PrLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCom_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Quantidade_min, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jCom_PrLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(Jl_quantidade1))))
                            .addGroup(jCom_PrLayout.createSequentialGroup()
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_DataVencimento)
                                    .addComponent(Data_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jl_descricao)))
                            .addGroup(jCom_PrLayout.createSequentialGroup()
                                .addComponent(jCom_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jCom_Produto1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jCom_PrLayout.setVerticalGroup(
            jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCom_PrLayout.createSequentialGroup()
                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCom_PrLayout.createSequentialGroup()
                        .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jCom_PrLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jCom_PrLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCom_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCom_Produto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jCom_PrLayout.createSequentialGroup()
                                        .addComponent(Jl_descricao)
                                        .addGap(31, 31, 31))
                                    .addGroup(jCom_PrLayout.createSequentialGroup()
                                        .addComponent(Jl_descricao1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jl_DataVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_Vencimento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCom_PrLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jCom_PrLayout.createSequentialGroup()
                        .addComponent(Jl_quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCom_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantidade_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCom_PrLayout.createSequentialGroup()
                        .addComponent(Jl_quantidade1)
                        .addGap(30, 30, 30)))
                .addGap(35, 35, 35)
                .addGroup(jCom_PrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCom_Pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCom_Pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String nascimentoInsert = Data_Vencimento.getText();
        String nascimento1 = nascimentoInsert.substring(0,2);
        String nascimento2 = nascimentoInsert.substring(3,5);
        String nascimento3 = nascimentoInsert.substring(6);
        String nascimentoInsert2 = nascimento3 + nascimento2 + nascimento1;
        String nascimentoFinal = nascimentoInsert2.replace("/","");
        String quantidade = Quantidade.getText();
        String quantidade_min = Quantidade_min.getText();
        String descricao = jT_Descricao.getText();
        String nome = (String)jCom_Produto.getSelectedItem();
        String nome1 = nome.replace("[","");
        String nomeFinal = nome1.replace("]","");
        System.out.println(nomeFinal);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
        String Data = formatter.format(date);
        String unidade = (String)jCom_Unidade.getSelectedItem();

        try{
        Connection con = connection.getConnection();
        Statement st = con.createStatement();
        
        String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        
        ArrayList<String> ncm = new ArrayList<String>();

            while (rs.next()) { 
            ncm.add(rs.getString(1));
            }
        String ncm1 = ncm.toString().replace("[","").replace("]","");
        st.executeUpdate("UPDATE produtos set ncm = '"+ncm1+"', nome = '"+nomeFinal+"' , quantidade = '"+quantidade+"' , quantidade_min = '"+quantidade_min+"', quantidade_total = quantidade_total + '"+quantidade+"' WHERE ncm = '"+ncm1+"' ");
        st.executeUpdate("INSERT INTO datas(validade,data_entrada,descricao,produtos_ncm) values ('"+nascimentoFinal+"','"+Data+"','"+descricao+"','"+ncm1+"')");
            System.out.println(quantidade);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        Tela_Principal = new Tela_Principal();
        Tela_Principal.setLocationRelativeTo(null);
        Tela_Principal.setSize (780,500);
        Tela_Principal.setVisible(true);
        Tela_Principal.setResizable(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void Voltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Voltar2ActionPerformed

    private void jCom_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_ProdutoActionPerformed
        
        String nome = (String)jCom_Produto.getSelectedItem();
        String nome1 = nome.replace("[","");
        try{
        Connection con = connection.getConnection();
        
        String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
   
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        
        ArrayList<String> ncm = new ArrayList<String>();

            while (rs.next()) { 
            ncm.add(rs.getString(1));
            }
        String ncm1 = ncm.toString().replace("[","").replace("]","");
        jTextNcm.setText(ncm1);
        
        String ncmConverted = ncm1.replace(".","");
        String query2 = "SELECT nome FROM produtos where char_length(nome) > 5 and ncm not like \"2209.00.00\" and \"2201.10.00\" and \"2501.00\" and \"2101.11.10\" and \"0409.00.00\" and \"0702.00.00\" and \"0707.00.00\" and \"1507.10.00\" and ncm like \"'"+ncmConverted+"'%\" order by nome";
        Statement st3 = con.createStatement();
        ResultSet rs2 = st3.executeQuery(query2);
        
        while (rs2.next()){
            jCom_Produto1.addItem(rs2.getString(1));
        }
        
        //st.executeUpdate("UPDATE produtos set nome = '"+nomeFinal+"' , quantidade = '"+quantidade+"' , quantidade_min = '"+quantidade_min+"', quantidade_total = quantidade_total + '"+quantidade+"' WHERE ncm = '"+ncm1+"' ");
        //st.executeUpdate("INSERT INTO datas(validade,data_entrada,descricao,produtos_ncm) values ('"+nascimentoFinal+"','"+Data+"','"+descricao+"','"+ncm1+"')");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCom_ProdutoActionPerformed

    private void Data_VencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_VencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data_VencimentoActionPerformed

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void Quantidade_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantidade_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantidade_minActionPerformed

    private void jTextNcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNcmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNcmActionPerformed

    private void jCom_Produto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_Produto1ActionPerformed
        String nome = (String)jCom_Produto1.getSelectedItem();
        String nome1 = nome.replace("[","");
        try{
        Connection con = connection.getConnection();
        
        String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
   
        Statement st2 = con.createStatement();
        ResultSet rs = st2.executeQuery(query);
        
        ArrayList<String> ncm = new ArrayList<String>();

            while (rs.next()) { 
            ncm.add(rs.getString(1));
            }
        String ncm1 = ncm.toString().replace("[","").replace("]","");
        jTextNcm.setText(ncm1);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCom_Produto1ActionPerformed

    private void jCom_UnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_UnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCom_UnidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciar_produto().setVisible(true);
            }
        });
    }
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Santos_2.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JFormattedTextField Data_Vencimento;
    private javax.swing.JLabel Jl_descricao;
    private javax.swing.JLabel Jl_descricao1;
    private javax.swing.JLabel Jl_quantidade;
    private javax.swing.JLabel Jl_quantidade1;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JTextField Quantidade_min;
    private javax.swing.JButton Voltar1;
    private javax.swing.JButton Voltar2;
    private javax.swing.JPanel jCom_Pr;
    private javax.swing.JComboBox<Object> jCom_Produto;
    private javax.swing.JComboBox<Object> jCom_Produto1;
    private javax.swing.JComboBox<String> jCom_Unidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_Descricao;
    private javax.swing.JTextField jTextNcm;
    private javax.swing.JLabel jl_DataVencimento;
    // End of variables declaration//GEN-END:variables
}
