/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connectionDB.connection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Humberto Sylvestre Nunes, Guilherme Mendes Mariano, Jorge Danillo Pereira, Jaffer da Silva Camacam Santos e Alexandre Morais Borges
 */
public class Movimentacao extends javax.swing.JFrame {
Tela_Principal Tela_Principal;
String myUrl = "jdbc:mysql://localhost:3306/santos_inocentes?useTimezone=true&serverTimezone=UTC";
private static final String USER = "ong";
private static final String PASS = "santos123@";
    /**
     * Creates new form 
     */
    public Movimentacao() {
        initComponents();
        setIcon();
        this.setTitle("Controle de Estoque - Movimentação");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCom_produto = new javax.swing.JComboBox<>();
        TextQuantidade = new javax.swing.JTextField();
        jCom_Unidade = new javax.swing.JComboBox<>();
        jCom_destino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelProduto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelProduto.setText("Produto:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Quantidade:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Destino:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Motivo:");

        jCom_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        try {
            Connection con = DriverManager.getConnection(myUrl, USER, PASS);
            String query = "SELECT nome FROM produtos order by nome";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            ArrayList<String> names = new ArrayList<String>();

            while (rs.next()) {
                //            names.add(rs.getString(1));
                jCom_produto.addItem(rs.getString(1));
                System.out.println(names);
            }
            //            jCom_Produto.addItem(names);

        } catch (SQLException ex) {
            Logger.getLogger(Gerenciar_produto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jCom_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_produtoActionPerformed(evt);
            }
        });

        TextQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQuantidadeActionPerformed(evt);
            }
        });

        jCom_Unidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramas", "Gramas", "Miligramas", "Litros", "Unidades", "Pacote", "Fardo", "Caixa" }));

        jCom_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        try {
            Connection con = DriverManager.getConnection(myUrl, USER, PASS);
            String query = "SELECT nome FROM unidade";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            ArrayList<String> names = new ArrayList<String>();

            while (rs.next()) {
                //            names.add(rs.getString(1));
                jCom_destino.addItem(rs.getString(1));
                jCom_destino.setSelectedItem(null);
                System.out.println(names);
            }
            //            jCom_Produto.addItem(names);

        } catch (SQLException ex) {
            Logger.getLogger(Gerenciar_produto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jCom_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCom_destinoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Outros:");

        Ok.setBackground(new java.awt.Color(204, 204, 204));
        Ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ok.setForeground(new java.awt.Color(0, 153, 255));
        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        Voltar.setBackground(new java.awt.Color(204, 204, 204));
        Voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voltar.setForeground(new java.awt.Color(0, 153, 255));
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(100, 80));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setPreferredSize(new java.awt.Dimension(100, 80));
        jScrollPane3.setViewportView(jTextArea2);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/santos_4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(LabelProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCom_produto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCom_Unidade, 0, 95, Short.MAX_VALUE))
                            .addComponent(jCom_destino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelProduto)
                            .addComponent(jCom_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCom_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCom_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        String nome = (String)jCom_produto.getSelectedItem();
        String quantidade = TextQuantidade.getText();
        String unidade = (String)jCom_Unidade.getSelectedItem();
        String destino = (String)jCom_destino.getSelectedItem();
        String descricao = jTextArea1.getText();
        String outros = jTextArea2.getText();
        System.out.println("Começa");
        int idunidade;
        String casa = "Casa das Mães", creche = "Creche", descarte = "Descarte ou Outros";
            if(destino.equals(casa)){ // Verifica qual string e atribui um idunidade
                idunidade = 1;
            try{ // Executa query para movimentar dados
            Connection con = connection.getConnection();
            Statement st = con.createStatement();

            String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement st2 = con.createStatement();
            ResultSet rs = st2.executeQuery(query);
            ArrayList<String> ncm = new ArrayList<String>();

                while (rs.next()) { 
                ncm.add(rs.getString(1));
                }
            String ncm1 = ncm.toString().replace("[","").replace("]","");
            st.executeUpdate("INSERT INTO movimentacao(quantidade, motivo, outros, unidade_idunidade) values ('"+quantidade+"','"+descricao+"','"+outros+"','"+idunidade+"')");
            st.executeUpdate("UPDATE produtos SET quantidade_total = quantidade_total -'"+quantidade+"'  WHERE ncm = '"+ncm1+"'");
                    } catch (SQLException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(destino.equals(creche)){ // Verifica qual string e atribui um idunidade
                idunidade = 2;
            try{ // Executa query para movimentar dados
            Connection con = connection.getConnection();
            Statement st = con.createStatement();

            String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement st2 = con.createStatement();
            ResultSet rs = st2.executeQuery(query);
            ArrayList<String> ncm = new ArrayList<String>();

                while (rs.next()) { 
                ncm.add(rs.getString(1));
                }
            String ncm1 = ncm.toString().replace("[","").replace("]","");
            st.executeUpdate("INSERT INTO movimentacao(quantidade, motivo, outros, unidade_idunidade) values ('"+quantidade+"','"+descricao+"','"+outros+"','"+idunidade+"')");
            st.executeUpdate("UPDATE produtos SET quantidade_total = quantidade_total -"+quantidade+"  WHERE ncm = '"+ncm1+"'");
                    } catch (SQLException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(destino.equals(descarte)){ // Verifica qual string e atribui um idunidade
                System.out.println("entra descarte");
                idunidade = 3;
            try{ // Executa query para movimentar dados
            Connection con = connection.getConnection();
            Statement st = con.createStatement();

            String query = "SELECT ncm FROM produtos WHERE nome = '"+nome+"' order by nome";
            Statement st2 = con.createStatement();
            ResultSet rs = st2.executeQuery(query);
            ArrayList<String> ncm = new ArrayList<String>();

                while (rs.next()) { 
                ncm.add(rs.getString(1));
                }
            String ncm1 = ncm.toString().replace("[","").replace("]","");
            st.executeUpdate("INSERT INTO movimentacao(quantidade, motivo, outros, unidade_idunidade) values ('"+quantidade+"','"+descricao+"','"+outros+"','"+idunidade+"')");
            st.executeUpdate("UPDATE produtos SET quantidade_total = quantidade_total -"+quantidade+"  WHERE ncm = '"+ncm1+"'");
                System.out.println("chegou mysql");
                    } catch (SQLException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
                System.out.println("fecha mysql");
            }
            System.out.println("termina");
        JOptionPane.showMessageDialog(null,"Concluído!");
            
    
    }//GEN-LAST:event_OkActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.dispose();
        Tela_Principal = new Tela_Principal();
        Tela_Principal.setLocationRelativeTo(null);
        Tela_Principal.setSize (780,500);
        Tela_Principal.setVisible(true);
        Tela_Principal.setResizable(false);
    }//GEN-LAST:event_VoltarActionPerformed

    private void jCom_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCom_produtoActionPerformed

    private void TextQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQuantidadeActionPerformed

    private void jCom_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCom_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCom_destinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimentacao().setVisible(true);
            }
        });
    }
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Santos_2.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelProduto;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField TextQuantidade;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jCom_Unidade;
    private javax.swing.JComboBox<String> jCom_destino;
    private javax.swing.JComboBox<String> jCom_produto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
